// Generates the PWA/app icons in /public from inline SVG sources.
// Run with: node scripts/generate-icons.mjs
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const publicDir = path.join(__dirname, '..', 'public');

const GREEN = '#15803d';

/** Full-bleed background (required for maskable icons and iOS, which apply their own mask/corners). */
function fullBleedSvg(glyphScale) {
  const fontSize = Math.round(512 * glyphScale);
  return `
    <svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512">
      <rect width="512" height="512" fill="${GREEN}" />
      <text x="256" y="256" text-anchor="middle" dominant-baseline="central"
        font-family="'DejaVu Sans', Arial, sans-serif" font-weight="700"
        font-size="${fontSize}" fill="#ffffff">C</text>
    </svg>
  `;
}

/** Rounded-square variant for the "any" purpose icon and favicon. */
function roundedSvg(size) {
  const fontSize = Math.round(size * 0.58);
  const radius = Math.round(size * 0.22);
  return `
    <svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
      <rect width="${size}" height="${size}" rx="${radius}" fill="${GREEN}" />
      <text x="${size / 2}" y="${size / 2}" text-anchor="middle" dominant-baseline="central"
        font-family="'DejaVu Sans', Arial, sans-serif" font-weight="700"
        font-size="${fontSize}" fill="#ffffff">C</text>
    </svg>
  `;
}

async function render(svg, size, outFile) {
  await sharp(Buffer.from(svg)).resize(size, size).png().toFile(path.join(publicDir, outFile));
  console.log('wrote', outFile);
}

async function main() {
  await mkdir(publicDir, { recursive: true });

  await render(roundedSvg(512), 512, 'icon-512.png');
  await render(roundedSvg(192), 192, 'icon-192.png');
  // Maskable icons need the glyph inside the ~80% "safe zone", full-bleed background.
  await render(fullBleedSvg(0.42), 512, 'icon-maskable-512.png');
  await render(fullBleedSvg(0.42), 192, 'icon-maskable-192.png');
  // iOS home-screen icon: no transparency, iOS applies its own rounding.
  await render(fullBleedSvg(0.55), 180, 'apple-touch-icon.png');

  await writeFile(
    path.join(publicDir, 'icon-note.txt'),
    'Icons generated by scripts/generate-icons.mjs. Replace with real brand assets before shipping to production.\n',
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
