/**
 * Postgres schema (Drizzle). Migrations are generated from this file with
 * `npm run db:generate` into /drizzle and applied on server start (instrumentation.ts).
 *
 * Budget data is normalized (months / incomes / expenses), but the repository
 * reassembles the exact `MonthData` shape from lib/budget, so the pure
 * calculation layer never changes because of the database.
 */
import { sql } from 'drizzle-orm';
import {
  boolean,
  check,
  date,
  foreignKey,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  primaryKey,
  text,
  timestamp,
  unique,
  uuid,
} from 'drizzle-orm/pg-core';
import type {
  CategoryKind,
  EmergencyCost,
  ExpenseSource,
  InstallmentAccounting,
  ModuleFlags,
  NavKey,
  SpecialCategoryColors,
  SpecialCategoryLabels,
  TopicConfig,
} from '../../budget/types';
import type { ReminderKind, TimeOfDay } from '../../reminders/types';

/** Every category an expense (or a template, or a plan) can have. */
const CATEGORY_KINDS = sql`in ('topic', 'fixedCost', 'unforeseen', 'reimbursable')`;

const createdAt = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow();
const updatedAt = () =>
  timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date());

// ---------------------------------------------------------------------------
// Auth (Better Auth). The export names (user, session, account, verification)
// and property names are the model/field names Better Auth looks up; the SQL
// names are snake_case. Ids are UUIDs generated by the database.
// ---------------------------------------------------------------------------
export const user = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').notNull().default(false),
  image: text('image'),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

export const session = pgTable(
  'sessions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    token: text('token').notNull().unique(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    userId: uuid('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index('sessions_user_id_idx').on(t.userId)],
);

export const account = pgTable(
  'accounts',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    accountId: text('account_id').notNull(),
    providerId: text('provider_id').notNull(),
    userId: uuid('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: timestamp('access_token_expires_at', { withTimezone: true }),
    refreshTokenExpiresAt: timestamp('refresh_token_expires_at', { withTimezone: true }),
    scope: text('scope'),
    /** Password hash (scrypt), written by Better Auth. */
    password: text('password'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index('accounts_user_id_idx').on(t.userId)],
);

export const verification = pgTable(
  'verifications',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    identifier: text('identifier').notNull(),
    value: text('value').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index('verifications_identifier_idx').on(t.identifier)],
);

// ---------------------------------------------------------------------------
// Budget
// ---------------------------------------------------------------------------

/** One row per user: envelope config + special category labels/colors (the `BudgetSettings` shape). */
export const budgetSettings = pgTable('budget_settings', {
  userId: uuid('user_id')
    .primaryKey()
    .references(() => user.id, { onDelete: 'cascade' }),
  topics: jsonb('topics').$type<TopicConfig[]>().notNull(),
  specialCategories: jsonb('special_categories').$type<SpecialCategoryLabels>().notNull(),
  specialCategoryColors: jsonb('special_category_colors')
    .$type<Partial<SpecialCategoryColors>>()
    .notNull()
    .default({}),
  /** Only a brand-new account's first row is created with false (see the repository's seed). */
  onboardingCompleted: boolean('onboarding_completed').notNull().default(true),
  /** The modules this user turned on. Anything absent is off. */
  modules: jsonb('modules').$type<Partial<ModuleFlags>>().notNull().default({}),
  /** The bottom bar the user picked, in order; null means the default (see `resolveNav`). */
  nav: jsonb('nav').$type<NavKey[]>(),
  /** Keys of the one-time notices this account already dismissed. */
  dismissedNotices: jsonb('dismissed_notices').$type<string[]>().notNull().default([]),
  updatedAt: updatedAt(),
});

/** One row per (user, competence month "YYYY-MM"). carryIn and topicsSnapshot keep the MonthData shape. */
export const months = pgTable(
  'months',
  {
    userId: uuid('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    month: text('month').notNull(),
    carryIn: jsonb('carry_in').$type<Record<string, number>>().notNull().default({}),
    topicsSnapshot: jsonb('topics_snapshot').$type<TopicConfig[]>().notNull().default([]),
    closed: boolean('closed').notNull().default(false),
    closedAt: timestamp('closed_at', { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    primaryKey({ columns: [t.userId, t.month] }),
    check('months_month_format', sql`${t.month} ~ '^[0-9]{4}-[0-9]{2}$'`),
  ],
);

/**
 * Ids are the client-generated ids of the MonthData entries (text: backups and old
 * local data may carry non-UUID ids), unique per user. `position` keeps the order
 * the entries had in the month, which is the order the UI lists them in.
 */
export const incomes = pgTable(
  'incomes',
  {
    userId: uuid('user_id').notNull(),
    id: text('id').notNull(),
    month: text('month').notNull(),
    source: text('source').notNull(),
    amount: numeric('amount', { mode: 'number' }).notNull(),
    date: date('date', { mode: 'string' }),
    position: integer('position').notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    primaryKey({ columns: [t.userId, t.id] }),
    foreignKey({
      columns: [t.userId, t.month],
      foreignColumns: [months.userId, months.month],
    }).onDelete('cascade'),
    index('incomes_user_month_idx').on(t.userId, t.month),
  ],
);

export const expenses = pgTable(
  'expenses',
  {
    userId: uuid('user_id').notNull(),
    id: text('id').notNull(),
    month: text('month').notNull(),
    categoryKind: text('category_kind').$type<CategoryKind>().notNull(),
    topicId: text('topic_id'),
    description: text('description').notNull(),
    amount: numeric('amount', { mode: 'number' }).notNull(),
    date: date('date', { mode: 'string' }).notNull(),
    /** `Expense.singleInstallmentCard`: the purchase lands on the credit-card bill. */
    card: boolean('card').notNull().default(false),
    /** Where the expense came from: a form, a recurring template, an instalment, ... */
    source: text('source').$type<ExpenseSource>(),
    /** Set when this expense is one instalment of a plan. */
    installmentId: text('installment_id'),
    installmentNumber: integer('installment_number'),
    position: integer('position').notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    primaryKey({ columns: [t.userId, t.id] }),
    foreignKey({
      columns: [t.userId, t.month],
      foreignColumns: [months.userId, months.month],
    }).onDelete('cascade'),
    index('expenses_user_month_idx').on(t.userId, t.month),
    // One expense per instalment, ever: launching the same charge twice is impossible.
    // (Rows with no instalment are unaffected — NULLs never collide in Postgres.)
    unique('expenses_installment_unique').on(t.userId, t.installmentId, t.installmentNumber),
    check('expenses_category_kind', sql`${t.categoryKind} ${CATEGORY_KINDS}`),
  ],
);

// ---------------------------------------------------------------------------
// Carteira: recurring expenses, instalment plans, invested reserve and cash
// ---------------------------------------------------------------------------

/** Templates for the expenses that repeat every month, launched with one tap. */
export const recurringExpenses = pgTable(
  'recurring_expenses',
  {
    userId: uuid('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    id: text('id').notNull(),
    categoryKind: text('category_kind').$type<CategoryKind>().notNull(),
    topicId: text('topic_id'),
    description: text('description').notNull(),
    amount: numeric('amount', { mode: 'number' }).notNull(),
    card: boolean('card').notNull().default(false),
    position: integer('position').notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    primaryKey({ columns: [t.userId, t.id] }),
    check('recurring_expenses_category_kind', sql`${t.categoryKind} ${CATEGORY_KINDS}`),
  ],
);

/**
 * A purchase split into monthly charges. Only what the user typed is stored: due dates, the
 * instalment value, how many are left and the end date are always computed.
 */
export const installments = pgTable(
  'installments',
  {
    userId: uuid('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    id: text('id').notNull(),
    name: text('name').notNull(),
    categoryKind: text('category_kind').$type<CategoryKind>().notNull(),
    topicId: text('topic_id'),
    firstDebitDate: date('first_debit_date', { mode: 'string' }).notNull(),
    count: integer('count').notNull(),
    totalAmount: numeric('total_amount', { mode: 'number' }).notNull(),
    accounting: text('accounting').$type<InstallmentAccounting>().notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    primaryKey({ columns: [t.userId, t.id] }),
    check('installments_category_kind', sql`${t.categoryKind} ${CATEGORY_KINDS}`),
    check('installments_accounting', sql`${t.accounting} in ('installment', 'upfront')`),
    check('installments_count', sql`${t.count} > 0`),
  ],
);

/** One row per user: the ticker used as an invested reserve and how many quotas are held. */
export const investmentReserves = pgTable('investment_reserves', {
  userId: uuid('user_id')
    .primaryKey()
    .references(() => user.id, { onDelete: 'cascade' }),
  ticker: text('ticker').notNull(),
  totalQuotas: numeric('total_quotas', { precision: 18, scale: 8, mode: 'number' })
    .notNull()
    .default(0),
  updatedAt: updatedAt(),
});

/** Quotas of the reserve earmarked for a topic (shown as "categoria" in the app). */
export const investmentBuckets = pgTable(
  'investment_buckets',
  {
    userId: uuid('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    id: text('id').notNull(),
    name: text('name').notNull(),
    topicId: text('topic_id'),
    quotas: numeric('quotas', { precision: 18, scale: 8, mode: 'number' }).notNull().default(0),
    position: integer('position').notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.id] })],
);

/**
 * Last known price per ticker (B3 code, no ".SA"). Global — a price is not personal — so a
 * portfolio with many assets shares the cache with every account.
 */
export const priceCache = pgTable('price_cache', {
  ticker: text('ticker').primaryKey(),
  price: numeric('price', { mode: 'number' }).notNull(),
  /** The asset's name as the source gave it. */
  name: text('name'),
  /** Which free source answered: 'b3' or 'yahoo' (lib/server/quotes.ts). */
  source: text('source'),
  fetchedAt: timestamp('fetched_at', { withTimezone: true }).notNull().defaultNow(),
});

/** What the cash report needs from each user. */
export const cashSettings = pgTable('cash_settings', {
  userId: uuid('user_id')
    .primaryKey()
    .references(() => user.id, { onDelete: 'cascade' }),
  reserveAccountAmount: numeric('reserve_account_amount', { mode: 'number' }).notNull().default(0),
  emergencyCosts: jsonb('emergency_costs').$type<EmergencyCost[]>().notNull().default([]),
  reserveMultiplier: integer('reserve_multiplier').notNull().default(6),
  updatedAt: updatedAt(),
});

// ---------------------------------------------------------------------------
// Notifications (Web Push)
// ---------------------------------------------------------------------------

/**
 * One row per device (browser) that accepted notifications. The endpoint is the push
 * service's address for that browser, unique worldwide: if another account signs in on the
 * same browser and turns notifications on, the row moves to that account.
 */
export const pushSubscriptions = pgTable(
  'push_subscriptions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    endpoint: text('endpoint').notNull().unique(),
    /** The browser's public key and auth secret, used to encrypt every payload. */
    p256dh: text('p256dh').notNull(),
    auth: text('auth').notNull(),
    /** To tell the devices apart in Settings ("Chrome no Android"). */
    userAgent: text('user_agent'),
    createdAt: createdAt(),
    /** Last time the push service accepted a notification for this device. */
    lastSuccessAt: timestamp('last_success_at', { withTimezone: true }),
  },
  (t) => [index('push_subscriptions_user_id_idx').on(t.userId)],
);

// ---------------------------------------------------------------------------
// Lembretes
// ---------------------------------------------------------------------------

/**
 * A reminder or a daily task. Which columns are used depends on `kind`: once → date + time
 * (+ notify_before_minutes), daily → times, weekly → weekdays + time, monthly → day_of_month +
 * time. Due days are always computed (lib/reminders), never stored ahead.
 */
export const reminders = pgTable(
  'reminders',
  {
    userId: uuid('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    id: text('id').notNull(),
    kind: text('kind').$type<ReminderKind>().notNull(),
    message: text('message').notNull(),
    date: date('date', { mode: 'string' }),
    time: text('time').$type<TimeOfDay>(),
    times: jsonb('times').$type<TimeOfDay[]>().notNull().default([]),
    weekdays: jsonb('weekdays').$type<number[]>().notNull().default([]),
    dayOfMonth: integer('day_of_month'),
    notifyBeforeMinutes: integer('notify_before_minutes'),
    repeat: boolean('repeat').notNull().default(true),
    /** Daily tasks only: when it was done (and so archived). */
    completedAt: timestamp('completed_at', { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    primaryKey({ columns: [t.userId, t.id] }),
    check('reminders_kind', sql`${t.kind} in ('once', 'daily', 'weekly', 'monthly')`),
  ],
);

/** "Realizado" for one due day of a once / weekly / monthly reminder. */
export const reminderCompletions = pgTable(
  'reminder_completions',
  {
    userId: uuid('user_id').notNull(),
    reminderId: text('reminder_id').notNull(),
    dueDate: date('due_date', { mode: 'string' }).notNull(),
    doneAt: timestamp('done_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.userId, t.reminderId, t.dueDate] }),
    foreignKey({
      columns: [t.userId, t.reminderId],
      foreignColumns: [reminders.userId, reminders.id],
    }).onDelete('cascade'),
  ],
);

/** Each user's reminder preferences; no row means the defaults (lib/reminders/types.ts). */
export const reminderSettings = pgTable('reminder_settings', {
  userId: uuid('user_id')
    .primaryKey()
    .references(() => user.id, { onDelete: 'cascade' }),
  repeatEnabled: boolean('repeat_enabled').notNull().default(true),
  repeatTimes: jsonb('repeat_times').$type<TimeOfDay[]>().notNull(),
  updatedAt: updatedAt(),
});

/**
 * Every notification slot already delivered. The primary key is what makes the scheduler safe to
 * run again (after a restart, or twice at once): a slot is sent only by whoever records it first.
 * Old rows are pruned by the scheduler.
 */
export const reminderDeliveries = pgTable(
  'reminder_deliveries',
  {
    userId: uuid('user_id').notNull(),
    reminderId: text('reminder_id').notNull(),
    slotAt: timestamp('slot_at', { withTimezone: true }).notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.userId, t.reminderId, t.slotAt] }),
    foreignKey({
      columns: [t.userId, t.reminderId],
      foreignColumns: [reminders.userId, reminders.id],
    }).onDelete('cascade'),
    index('reminder_deliveries_slot_at_idx').on(t.slotAt),
  ],
);

/** When each background job last ran (the scheduler picks up from there after a restart). */
export const jobRuns = pgTable('job_runs', {
  name: text('name').primaryKey(),
  lastRunAt: timestamp('last_run_at', { withTimezone: true }).notNull(),
});

// ---------------------------------------------------------------------------
// Monitor de Gmail
// ---------------------------------------------------------------------------

/**
 * The Gmail account connected with "Login com Google" (read-only scope). The refresh token is
 * stored encrypted (AES-256-GCM with ENCRYPTION_KEY); `last_history_id` is where the next check
 * starts, so only e-mails received after it are read.
 */
export const gmailAccounts = pgTable(
  'gmail_accounts',
  {
    userId: uuid('user_id')
      .primaryKey()
      .references(() => user.id, { onDelete: 'cascade' }),
    email: text('email').notNull(),
    refreshToken: text('refresh_token').notNull(),
    lastHistoryId: text('last_history_id'),
    /** ok, error (the last check failed, it tries again) or reconnect (Google refused the token). */
    status: text('status').$type<'ok' | 'error' | 'reconnect'>().notNull().default('ok'),
    lastError: text('last_error'),
    lastCheckedAt: timestamp('last_checked_at', { withTimezone: true }),
    connectedAt: timestamp('connected_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [check('gmail_accounts_status', sql`${t.status} in ('ok', 'error', 'reconnect')`)],
);

export const gmailKeywords = pgTable(
  'gmail_keywords',
  {
    userId: uuid('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    id: uuid('id').notNull().defaultRandom(),
    keyword: text('keyword').notNull(),
    createdAt: createdAt(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.id] })],
);

/**
 * One row per e-mail that matched (correction 13): the primary key is what keeps an e-mail from
 * being notified twice, and the rows are the history shown on the screen.
 */
export const gmailAlerts = pgTable(
  'gmail_alerts',
  {
    userId: uuid('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    messageId: text('message_id').notNull(),
    keywords: jsonb('keywords').$type<string[]>().notNull(),
    subject: text('subject').notNull(),
    from: text('from').notNull(),
    receivedAt: timestamp('received_at', { withTimezone: true }).notNull(),
    notifiedAt: timestamp('notified_at', { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.userId, t.messageId] }),
    index('gmail_alerts_user_received_idx').on(t.userId, t.receivedAt),
  ],
);
